version: '3.2'
services:
  db:
    image: mongo:3.4-jessie
    volumes:
      - type: volume
        source: mongo_db
        target: /data/db
        volume:
          nocopy: true
      - type: volume
        source: mongo_configdb
        target: /data/configdb
        volume:
          nocopy: true
    ports:
      - "127.0.0.1:27020:27017"
  app:
    image: oculaire-app:latest
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /opt/oculaire
    ports:
      - "127.0.0.1:8081:8081"
    user: ${UID:-1000}:${GID:-1000}
    env_file: .env
  webserver:
    image: oculaire-webserver:latest
    build:
      context: .
      dockerfile: webserver.dockerfile
    ports:
      - "127.0.0.1:81:81"
      - "127.0.0.1:444:444"
    env_file: .env
volumes:
  mongo_db:
  mongo_configdb:
